CREATE TABLE IF NOT EXISTS public.mail_batches (
  batch_id TEXT PRIMARY KEY,
  region TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'generated'
    CHECK (status IN ('generated', 'approved', 'submitted', 'mailed', 'cancelled')),
  record_count INTEGER NOT NULL DEFAULT 0,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  submitted_at TIMESTAMPTZ,
  mailed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mail_batch_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id TEXT NOT NULL REFERENCES public.mail_batches(batch_id) ON DELETE CASCADE,
  zpid BIGINT NOT NULL REFERENCES public.listings(zpid) ON DELETE RESTRICT,
  postcard_type TEXT NOT NULL CHECK (postcard_type IN ('just_listed', 'sold')),
  status TEXT NOT NULL DEFAULT 'generated'
    CHECK (status IN ('generated', 'mailed', 'cancelled')),
  address_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  mailed_at TIMESTAMPTZ,
  UNIQUE (batch_id, zpid, postcard_type)
);

CREATE TABLE IF NOT EXISTS public.outreach_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zpid BIGINT NOT NULL REFERENCES public.listings(zpid) ON DELETE RESTRICT,
  batch_id TEXT NOT NULL REFERENCES public.mail_batches(batch_id) ON DELETE RESTRICT,
  event_type TEXT NOT NULL CHECK (event_type IN ('just_listed_postcard_mailed', 'sold_postcard_mailed')),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (batch_id, zpid, event_type)
);

ALTER TABLE public.mail_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mail_batch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outreach_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.stage_postcard_batch(
  p_batch_id TEXT,
  p_region TEXT,
  p_items JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE item JSONB;
BEGIN
  IF p_batch_id IS NULL OR p_batch_id = '' OR jsonb_typeof(p_items) <> 'array' THEN
    RAISE EXCEPTION 'Invalid postcard batch payload';
  END IF;
  INSERT INTO mail_batches(batch_id, region, status, record_count)
  VALUES (p_batch_id, p_region, 'generated', jsonb_array_length(p_items))
  ON CONFLICT (batch_id) DO UPDATE SET
    record_count = EXCLUDED.record_count,
    updated_at = now()
  WHERE mail_batches.status = 'generated';

  DELETE FROM mail_batch_items WHERE batch_id = p_batch_id AND status = 'generated';
  FOR item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO mail_batch_items(batch_id, zpid, postcard_type, address_snapshot)
    VALUES (
      p_batch_id,
      (item->>'zpid')::BIGINT,
      item->>'postcard_type',
      item - 'zpid' - 'postcard_type'
    );
  END LOOP;
  RETURN jsonb_build_object('batch_id', p_batch_id, 'status', 'generated', 'record_count', jsonb_array_length(p_items));
END;
$$;

CREATE OR REPLACE FUNCTION public.confirm_postcard_batch_mailed(p_batch_id TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_now TIMESTAMPTZ := now(); v_count INTEGER;
BEGIN
  PERFORM 1 FROM mail_batches WHERE batch_id = p_batch_id AND status IN ('generated', 'approved', 'submitted') FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch not found or already finalized: %', p_batch_id; END IF;

  INSERT INTO outreach_events(zpid, batch_id, event_type, occurred_at)
  SELECT zpid, batch_id,
    CASE postcard_type WHEN 'sold' THEN 'sold_postcard_mailed' ELSE 'just_listed_postcard_mailed' END,
    v_now
  FROM mail_batch_items WHERE batch_id = p_batch_id AND status = 'generated'
  ON CONFLICT DO NOTHING;

  UPDATE listings l SET
    status = CASE WHEN i.postcard_type = 'sold' THEN 'sold_archived' ELSE 'active' END,
    just_listed_postcard_sent_at = CASE WHEN i.postcard_type = 'just_listed' THEN v_now ELSE l.just_listed_postcard_sent_at END,
    sold_postcard_sent_at = CASE WHEN i.postcard_type = 'sold' THEN v_now ELSE l.sold_postcard_sent_at END,
    last_postcard_sent_at = v_now,
    last_postcard_batch_id = p_batch_id,
    last_postcard_type_sent = i.postcard_type,
    postcard_send_count = COALESCE(l.postcard_send_count, 0) + 1,
    postcard_skip_reason = NULL
  FROM mail_batch_items i
  WHERE i.batch_id = p_batch_id AND i.status = 'generated' AND i.zpid = l.zpid;

  UPDATE mail_batch_items SET status = 'mailed', mailed_at = v_now
  WHERE batch_id = p_batch_id AND status = 'generated';
  GET DIAGNOSTICS v_count = ROW_COUNT;
  UPDATE mail_batches SET status = 'mailed', mailed_at = v_now, updated_at = v_now WHERE batch_id = p_batch_id;
  RETURN jsonb_build_object('batch_id', p_batch_id, 'status', 'mailed', 'record_count', v_count);
END;
$$;

REVOKE ALL ON FUNCTION public.stage_postcard_batch(TEXT, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.confirm_postcard_batch_mailed(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.stage_postcard_batch(TEXT, TEXT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.confirm_postcard_batch_mailed(TEXT) TO service_role;
